"""empty message

Revision ID: 11c6c20e7f2
Revises: 1e3095d3a98
Create Date: 2015-10-17 21:48:44.606869

"""

# revision identifiers, used by Alembic.
revision = '11c6c20e7f2'
down_revision = '1e3095d3a98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
