"""empty message

Revision ID: 4cdb6e3444d
Revises: b69f273d27
Create Date: 2015-10-13 17:26:59.841615

"""

# revision identifiers, used by Alembic.
revision = '4cdb6e3444d'
down_revision = 'b69f273d27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
